# Generated by Django 3.2.5 on 2022-02-17 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fabfacility_website_theme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_location', models.CharField(max_length=255)),
                ('project_pic', models.ImageField(upload_to='ProjectPictures')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
